<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>RanGoFood</AssemblyName>
    <RootNamespace>Pedeai</RootNamespace>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Quartz" Version="3.13.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\RanGoFood.png" Link="RanGoFood.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AUDIO.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!-- Metadados dos arquivos Designer para o VS exibir corretamente -->
  <ItemGroup>
    <Compile Update="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Form1.Designer.cs">
      <DependentUpon>Form1.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroCategoria.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroCategoria.Designer.cs">
      <DependentUpon>frmCadastroCategoria.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroCliente.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroCliente.Designer.cs">
      <DependentUpon>frmCadastroCliente.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroCupom.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroCupom.Designer.cs">
      <DependentUpon>frmCadastroCupom.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroFornecedor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroFornecedor.Designer.cs">
      <DependentUpon>frmCadastroFornecedor.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroProduto.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroProduto.Designer.cs">
      <DependentUpon>frmCadastroProduto.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmPedidoManual.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmPedidoManual.Designer.cs">
      <DependentUpon>frmPedidoManual.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmAvisos.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmAvisos.Designer.cs">
      <DependentUpon>frmAvisos.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmMovimentacoesDia.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmMovimentacoesDia.Designer.cs">
      <DependentUpon>frmMovimentacoesDia.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmRelatorioFinanceiro.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmRelatorioFinanceiro.Designer.cs">
      <DependentUpon>frmRelatorioFinanceiro.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmLicenca.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmLicenca.Designer.cs">
      <DependentUpon>frmLicenca.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroBairro.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroBairro.Designer.cs">
      <DependentUpon>frmCadastroBairro.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroMarmita.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmAutorizacao.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmAutorizacao.Designer.cs">
      <DependentUpon>frmAutorizacao.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroGasto.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroGasto.Designer.cs">
      <DependentUpon>frmCadastroGasto.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmCadastroNecessidade.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCadastroNecessidade.Designer.cs">
      <DependentUpon>frmCadastroNecessidade.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmEmpresa.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmEmpresa.Designer.cs">
      <DependentUpon>frmEmpresa.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmEntradaMercadoria.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmEntradaMercadoria.Designer.cs">
      <DependentUpon>frmEntradaMercadoria.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmEstoque.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmEstoque.Designer.cs">
      <DependentUpon>frmEstoque.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmLogin.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmLogin.Designer.cs">
      <DependentUpon>frmLogin.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmSelecionarCliente.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmSelecionarCliente.Designer.cs">
      <DependentUpon>frmSelecionarCliente.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmTurno.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmTurno.Designer.cs">
      <DependentUpon>frmTurno.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmRelatorioTurno.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmRelatorioTurno.Designer.cs">
      <DependentUpon>frmRelatorioTurno.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmConexao.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmConexao.Designer.cs">
      <DependentUpon>frmConexao.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmWhatsApp.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmWhatsApp.Designer.cs">
      <DependentUpon>frmWhatsApp.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmConsultarPedido.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmConsultarPedido.Designer.cs">
      <DependentUpon>frmConsultarPedido.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\frmFidelizacao.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmFidelizacao.Designer.cs">
      <DependentUpon>frmFidelizacao.cs</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\frmCadastroProduto.resx">
      <DependentUpon>frmCadastroProduto.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>